{
  "phases": {
    "setup": "python -m venv /opt/venv && . /opt/venv/bin/activate",
    "install": "pip install -r requirements.txt",
    "start": "gunicorn donations.wsgi:application --bind 0.0.0.0:$PORT"
  }
}
